
package Modelo;

import Vista.VentanaContinuarAlimentos;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class pnlDos extends javax.swing.JPanel {
    JButton btninventario;
    JLabel jLabel1;
    JLabel jLabel2;
    JLabel jLabel4;
    VentanaContinuarAlimentos objAlimento = new VentanaContinuarAlimentos();
    public pnlDos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new JLabel();
        btninventario = new JButton();
        jLabel2 = new JLabel();
        jLabel4 = new JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/collection.png"))); // NOI18N
        jLabel1.setText("Productos");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 347, -1));

        btninventario.setBackground(new java.awt.Color(153, 153, 0));
        btninventario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btninventario.setForeground(new java.awt.Color(255, 255, 255));
        btninventario.setText("Ir al Inventario");
        btninventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninventario.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btninventarioAP(evt);
            }
        });
        add(btninventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 222, 83));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenVivanda1.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 686, 350));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBlanco.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 620));
    }// </editor-fold>                        

    private void btninventarioAP(ActionEvent evt) {                                         

        objAlimento.setVisible(true);
        // Este codigo sirve para Cerrar un panel , ya que con el "this.dispose" solo se pueden
        // cerrar jframe y este es un panel, es por ello que se usa el siguiente codigo :D
        Window w = SwingUtilities.getWindowAncestor(pnlDos.this);
       w.setVisible(false);   
    }                                        
                    
                     
}

